apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32000
  type: NodePort