apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: migration
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
      nodePort: 30000
  type: NodePort
  selector:
    app: postgres
